name: "Multi event pipeline/workflow"
on:
   push:
     branches:
      - master

jobs:
 on-push:
   runs-on: Ubantu-latest
   steps:
      - name: "running on master push"
        run: echo "Running on master push"
